### ISSUE TITLE
Experiences with latest K40 and Python 3.8.6

### ISSUE THREAD

**Issue by mcaramb** [stephenhouser/k40-whisperer#2]
Hey, thanks for the great app creator, but am having trouble with the resulting app. Lots of options are missing on several pages, and the Raster Screen is completely blank. This is probably due to any or all of the following untested options. So just letting you know... here's my process for a current install:

1. Download the latest .src file from scorchworks and unzip into the Applications folder and rename the folder K40_Whisperer

https://www.scorchworks.com/K40whisperer/k40whisperer.html
ie: https://www.scorchworks.com/K40whisperer/K40_Whisperer-0.54_src.zip

2. Open Terminal. Do not sudo

3. Download Homebrew (best to use bash now instead of ruby)

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

4. Install Inkscape

brew tap homebrew/cask
brew cask install xquartz

(will need to enter computer password. Will be a long pause after)

brew cask install inkscape

(long pause)

5. Install libusb for communication with the controller

brew install libusb

6. Install latest pyinstaller Python

brew install pyinstaller

(brew no longer supports python@2. It will download 3.8.6 or 3.9 as a prerequisite for pyinstaller. I don't do brew install python as the version of pyinstaller doesn't match the version of python this goes to. So, by running pyinstaller first you are sure to get the right version of python as a requisite automatically.

(note version ie: python 3.8.6, 3.9.0, etc.. will dictate how to use pip.. ie: pip3 not pip)

7. Install python setup tools

pip3 install --upgrade pip setuptools

cd /Volumes/MacHD/Applications/k40_whisperer

8. Install K40 requirements

pip3 install -r requirements.txt

9. Install pyenv and set path

brew install pyenv

(use version home-brew installed. ie: 3.8.6)

PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.8.6
pyenv global 3.8.6

hash -r

(rehash isn't a bash command)

10. Update from the latest K40_Whisperer.src file

./update_macOS.sh -u https://www.scorchworks.com/K40whisperer/K40_Whisperer-0.54_src.zip

**Comment by stephenhouser** [comment]
Apologies for not seeing your issue earlier. I'm not sure what your question might be or what assistance you are looking for. Is it getting this working with Python 3.8?

**Comment by mcaramb** [comment]
Yes, that is still the issue. Running MacOS 15, and/or the latest Python 3.8/3.9. I've managed to get the script running with latest Python  (see my process above), but your app compiler sadly doesn't comply yet as you mentioned.
Thanks for the update!

**Comment by stephenhouser** [comment]
My build does use Python 3.7.2. I've got it marginally working with 3.9.1 on Big Sur. Hoping to have a .dmg shortly.

**Comment by stephenhouser** [comment]
I built a new `.dmg` with Python 3.9.1. A few differences from your recipe.
* I use `pyenv` to install different python versions, not Homebrew (your step 6)
* I did not update setuptools (step 7). Though not sure if I did at an earlier time and just forgot.
* I think it's `pyenv rehash` (step 9).
* I used K40 Whisperer v0.56 (step 10) as it's the latest as of today.

Not sure if this helps you build it yourself, but ... well... there you go.

**Comment by mcaramb** [comment]
thanks man! will give it a try
    On Monday, January 25, 2021, 01:53:31 PM CST, Stephen Houser <notifications@github.com> wrote:  
 
 


I built a new .dmg with Python 3.9.1. A few differences from your recipe.
   
   - I use pyenv to install different python versions, not Homebrew (your step 6)
   - I did not update setuptools (step 7). Though not sure if I did at an earlier time and just forgot.
   - I think it's pyenv rehash (step 9).
   - I used K40 Whisperer v0.56 (step 10) as it's the latest as of today.

Not sure if this helps you build it yourself, but ... well... there you go.

**Comment by stephenhouser** [comment]
I did a bit more tweaking of the build process as I found some inconsistencies. I'm going to close this issue with what I think is now a reliable, repeatable build process that should work on OSX 10.10 up through macOS 11.1. `build-macOS.sh` has the gory details.

**Comment by mcaramb** [comment]
nice! thanks man, will try the build in a bit
    On Friday, January 29, 2021, 04:02:59 PM CST, Stephen Houser <notifications@github.com> wrote:  
 
 


I did a bit more tweaking of the build process as I found some inconsistencies. I'm going to close this issue with what I think is now a reliable, repeatable build process that should work on OSX 10.10 up through macOS 11.1. build-macOS.sh has the gory details.
